# @package _global_

# Defaults for training for the PushT dataset as per https://github.com/real-stanford/diffusion_policy.
# Note: We do not track EMA model weights as we discovered it does not improve the results. See
#       https://github.com/huggingface/lerobot/pull/134 for more details.

seed: 100000
dataset_repo_id: notmahi/tutorial-ball-top-20
dataset_version: main


training:
  offline_steps: 1796
  online_steps: 0
  eval_freq: 0
  save_freq: 5000
  log_freq: 250
  save_checkpoint: true

  batch_size: 128
  lr: 1e-5
  lr_backbone: 1e-5
  weight_decay: 1e-4
  grad_clip_norm: 10
  online_steps_between_rollouts: 1

  delta_timestamps:
    action: "[i / ${fps} for i in range(${policy.action_chunk_size})]"
    observation.state: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"

eval:
  n_episodes: 50
  batch_size: 50

# See `configuration_act.py` for more details.
policy:
  name: nn

  # Input / output structure.
  n_obs_steps: 1
  action_chunk_size: 1 # chunk_size

  input_shapes:
    # TODO(rcadene, alexander-soare): add variables for height and width from the dataset/env?
    observation.state: ["${env.state_dim}"]
  output_shapes:
    action: ["${env.action_dim}"]

  # Normalization / Unnormalization
  input_normalization_modes:
    observation.state: mean_std
  output_normalization_modes:
    action: mean_std
  database_size: 230000
  topk: 5

  # Possible modes: weighted_avg, sample
  action_sample_mode: sample
  distance_metric: 2
  weights: [[10.0, 10.0, 1.0, 1.0]]